<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_radius" value="0.18" />
    <xacro:property name="base_length" value="0.15" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_thickness" value="0.036" />
    <xacro:property name="base_mass" value="2.0" />
    <xacro:property name="wheel_mass" value="0.33" />
    <xacro:property name="shaft_mass" value="0.01" />

    <xacro:property name="motor_shaft_radius" value="0.002" />
    <xacro:property name="motor_shaft_length" value="0.005475"/>

    <link name="base_footprint" />

    <joint name="base_footprint_base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0" />
    </joint>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0.0 0.0 ${base_length / 2.0}" rpy="0.0 0.0 0.0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 ${base_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" l ="${base_length}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <xacro:include filename="wheel.xacro" />
    
    <xacro:wheel parent="base_link" suffix="1" theta="${PI}"/>
    <xacro:wheel parent="base_link" suffix="2" theta="-${PI/3}"/>
    <xacro:wheel parent="base_link" suffix="3" theta="${PI/3}"/>

</robot>