<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_radius" value="0.18" />
    <xacro:property name="base_length" value="0.15" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_length" value="0.036" />
    
    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0.0 0.0 ${base_length / 2.0}" rpy="0.0 0.0 0.0" />
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 ${base_length / 2.0}" rpy="0 0 0" />
        </collision>
        <xacro:cylinder_inertia m="2.0" r="${base_radius}" l ="${base_length}"
                           xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_footprint_base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0" />
    </joint>

    <xacro:macro name="wheel_link" params="suffix color">
        <link name="wheel_${suffix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 ${-1*wheel_length / 2.0}" rpy="0 0 0" />
                <material name="${color}" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 ${-1*wheel_length / 2.0}" rpy="0 0 0" />
            </collision>
<<<<<<< HEAD
            <xacro:cylinder_inertia m="0.33" r="${wheel_radius}" l="${wheel_length}" 
=======
            <xacro:cylinder_inertia m="1.0" r="${wheel_radius}" l="${wheel_length}" 
>>>>>>> origin/TUF
                                    xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:wheel_link suffix="1" color="grey" />
    
    <xacro:wheel_link suffix="2" color="orange"/>

    <xacro:wheel_link suffix="3" color="yellow"/>


    <joint name="base_wheel_1_joint" type="continuous">
        <parent link="base_link" />
        <child link="wheel_1_link" />
        <origin xyz = "${base_radius*-1} 0 0" rpy="0 ${pi/2.0} 0" />
        <!-- <origin xyz ="0 0 0" rpy="0 0 0" /> -->
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_wheel_3_joint" type="continuous">
        <parent link="base_link" />
        <child link="wheel_3_link" />
        <origin xyz="${base_radius * 0.5} ${base_radius * 0.866} 0" rpy="0 ${pi/2.0} ${(4.0 * pi) / 3.0}" />
        <!-- <origin xyz ="0 0 0" rpy="0 0 0" /> -->
        <axis xyz="0 0 1" />
    </joint>

    <joint name="base_wheel_2_joint" type="continuous">
        <parent link="base_link" />
        <child link="wheel_2_link" />
        <origin xyz="${base_radius * 0.5} ${base_radius * -0.866} 0" rpy="0 ${pi/2.0} ${(2.0 * pi) / 3.0}" />
        <!-- <origin xyz ="0 0 0" rpy="0 0 0" /> -->
        <axis xyz="0 0 1" />
    </joint>

</robot>