controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz
    

    arm_controller:
      type: position_controllers/JointGroupPositionController

    # joint1_position:
    #   type: position_controllers/JointGroupPositionController

    # joint2_position:
    #   type: position_controllers/JointGroupPositionController

    # joint3_position:
    #   type: position_controllers/JointGroupPositionController

    # joint4_position:
    #   type: position_controllers/JointGroupPositionController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

# joint1_position:
#   ros__parameters:
#     joints:
#       - joint1
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

# joint2_position:
#   ros__parameters:
#     joints:
#       - joint2
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

# joint3_position:
#   ros__parameters:
#     joints:
#       - joint3
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

# joint4_position:
#   ros__parameters:
#     joints:
#       - joint4
#     command_interfaces:
#       - position
#     state_interfaces:
#       - position
#       - velocity

# hand_controller:
#   ros__parameters:
#     joint: gripper

joint_state_broadcaster:
  ros__parameters:
    
   
    use_local_topics: false
    use_urdf_to_filter: true